### ISSUE TITLE
[Bug] Addon says missing dependencies

### ISSUE THREAD

**Issue by frgrtyt** [DeathGOD7/FIFA-3D-Importer-Exporter#4]
**Describe the bug**
A clear and concise description of what the bug is. Just saying the addon won't work will make the chances of you getting help and support slim or none. 

**To Reproduce**
3. Try to import '....'
4. See an error

**Expected behavior**

**Screenshots**

**Blender Info (please complete the following information):**
 - Version [e.g. 2.80]
 - Architecture [e.g 32bit / 64bit] (Only Blender 2.80 supports 32-Bit) 

**Log File**
If there is any log file of today in "C:\Users\{YOUR USERNAME}\Documents\SE7EN\FIFA 3D\Logs", please upload it to "paste.gg" or "hastebin.com" and post the link here.

**Additional context**
Please open the system console of Blender (Window > Toggle System Console)
Copy all the things you see and upload it to "paste.gg" or "hastebin.com" and post the link here.
---- error ------

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\fifa_tools\__init__.py", line 64, in <module>
    from fifa_tools import fifa3D_layout
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\fifa_tools\fifa3D_layout.py", line 33, in <module>
    from fifa_tools.scripts import fifa3D_operators
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\fifa_tools\scripts\fifa3D_operators.py", line 34, in <module>
    from fifa_tools.scripts import fifa3D_se7en , fifa3D_helper
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\fifa_tools\scripts\fifa3D_se7en.py", line 24, in <module>
    from FIFALibrary20 import *
ModuleNotFoundError: No module named 'FIFALibrary20'

**Comment by frgrtyt** [comment]
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\fifa_tools\__init__.py", line 64, in <module>
    from fifa_tools import fifa3D_layout
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\fifa_tools\fifa3D_layout.py", line 33, in <module>
    from fifa_tools.scripts import fifa3D_operators
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\fifa_tools\scripts\fifa3D_operators.py", line 34, in <module>
    from fifa_tools.scripts import fifa3D_se7en , fifa3D_helper
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\fifa_tools\scripts\fifa3D_se7en.py", line 19, in <module>
    ref1 = clr.AddReference('FIFALibrary_v21.11.28.0_x64')
System.IO.FileNotFoundException: Unable to find assembly 'FIFALibrary_v21.11.28.0_x64'.
   위치: Python.Runtime.CLRModule.AddReference(String name)

**Comment by RexSE7EN** [comment]
Please use the issue template properly.
And by looking at the error, it seems the dll isn't loaded properly cause the blender installation is at C drive (local-user installation in appdata folder).

**Comment by frgrtyt** [comment]
I corrected the path and got the following error
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\addons\fifa_tools\__init__.py", line 51, in <module>
    from fifa_tools import se7en_helper
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\addons\fifa_tools\se7en_helper.py", line 19, in <module>
    files = os.listdir(pyNET)
FileNotFoundError: [WinError 3] 지정된 경로를 찾을 수 없습니다: 'C:\\Users\\Administrator\\AppData\\Roaming\\Blender Foundation\\Blender\\2.93\\scripts\\addons\\fifa_tools\\redist\\PythonNET'

**Comment by RexSE7EN** [comment]
Remove the addon and clear the clear files of this path (if any remains) and try reinstalling again. And if you can use the zipped blender version in another drive than `C:`.

`C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\fifa_tools`
And this :
`C:\Users\Administrator\Documents\SE7EN`

**Comment by frgrtyt** [comment]
I've already tried deleting it several times, but it's the same.

**Comment by RexSE7EN** [comment]
```
FileNotFoundError: [WinError 3] 지정된 경로를 찾을 수 없습니다: 'C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\fifa_tools\redist\PythonNET'
```
This states that the file or folder of redist is not where it's supposed to be.

That means these files :
![image](https://github.com/DeathGOD7/FIFA-3D-Importer-Exporter/assets/36422471/daa083f9-3428-4045-9cca-e1d3bdfc8f1c)


Without these files, the addon won't even function.

**Comment by frgrtyt** [comment]
Traceback (most recent call last):
  File "C:\Blender 2.93\2.93\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\fifa_tools\__init__.py", line 64, in <module>
    from fifa_tools import fifa3D_layout
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\fifa_tools\fifa3D_layout.py", line 33, in <module>
    from fifa_tools.scripts import fifa3D_operators
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\fifa_tools\scripts\fifa3D_operators.py", line 34, in <module>
    from fifa_tools.scripts import fifa3D_se7en , fifa3D_helper
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\fifa_tools\scripts\fifa3D_se7en.py", line 20, in <module>
    ref1 = clr.AddReference('FIFALibrary_v22.02.11_x64_Beta')
System.IO.FileNotFoundException: Unable to find assembly 'FIFALibrary_v22.02.11_x64_Beta'.
   위치: Python.Runtime.CLRModule.AddReference(String name)

**Comment by frgrtyt** [comment]
What is the compatible version?

**Comment by curung** [comment]
This is my sub-account Please tell me how to solve it

**Comment by RexSE7EN** [comment]
```
File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\fifa_tools\scripts\fifa3D_se7en.py", line 20, in
ref1 = clr.AddReference('FIFALibrary_v22.02.11_x64_Beta')
System.IO.FileNotFoundException: Unable to find assembly 'FIFALibrary_v22.02.11_x64_Beta'.
위치: Python.Runtime.CLRModule.AddReference(String name)
```

The above error means the required dll is missing due to buggy installation.
Check the folder named "SE7EN" in the Documents folder.

**Comment by dolixec** [comment]
I'll tell you how to fix it, since I tried to solve the problem today and just found out how to do it. This happens because you're using the files that are on the main github. You have to go into the releases and use the assets that are provided there. The problem that you encountered was because the file that you generated in the Documents "FIFALibrary_v22.02.11_x64_Beta" was an older version than the one that got generated in your folder.

**Comment by RexSE7EN** [comment]
✅ dolixec answer marked as solution.
